/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LEFT_MOT_PWM.h"
#include "Clock_1.h"
#include "LEFT_MOT_CNTRL_aliases.h"
#include "LEFT_MOT_CNTRL.h"
#include "RIGHT_MOT_CNTRL_aliases.h"
#include "RIGHT_MOT_CNTRL.h"
#include "IR_R_aliases.h"
#include "IR_R.h"
#include "IR_L_aliases.h"
#include "IR_L.h"
#include "LEFT_MOT_DIR_aliases.h"
#include "LEFT_MOT_DIR.h"
#include "RIGHT_MOT_DIR_aliases.h"
#include "RIGHT_MOT_DIR.h"
#include "START_aliases.h"
#include "START.h"
#include "RIGHT_MOT_PWM.h"
#include "Reg_PWM.h"
#include "ADC_SAR_1.h"
#include "ADC_in_aliases.h"
#include "ADC_in.h"
#include "LCD_Char_1.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

